apiVersion: v1
kind: Pod
metadata:
  name: nginx4-minion2
  labels:
    env: test
spec:
  nodeName: henrique-k8s-minion-2
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    type: minion

