apiVersion: v1
kind: Pod
metadata:
  name: random-limits-high-res-8
  # annotations:
  #   scheduler.alpha.kubernetes.io/name: mine
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
    resources:
      requests:
        memory: "256Mi"
        cpu: "350m"
      limits:
        memory: "10G"
        cpu: "10"
  - name: log-truncator
    image: busybox
    command:
    - /bin/sh
    args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
    volumeMounts:
    - mountPath: /logdir
      name: nginx-logs
  volumes:
  - name: nginx-logs
    emptyDir: {}
